
# Database settings
database:
  url: "mongodb://<user>:<password>@<server>:<port>/<dbname>?retryWrites=true&w=majority&authSource=admin"
  db: "catalog"
  timeout: 5

# Server settings
server:
  host: "localhost"
  port: ":8082"
